; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zve64x,+xsmtvdot \
; RUN:   -verify-machineinstrs -target-abi=ilp32 | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zve64x,+xsmtvdot \
; RUN:   -verify-machineinstrs -target-abi=lp64 | FileCheck %s

define <vscale x 4 x i32> @intrinsic_vmadotus_vv_nxv4i32_nxv8i8_nxv8i8(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vmadotus_vv_nxv4i32_nxv8i8_nxv8i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    smt.vmadotus v8, v10, v11
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 4 x i32> @llvm.riscv.smt.vmadotus.nxv4i32.nxv8i8.nxv8i8(
    <vscale x 4 x i32> %0,
    <vscale x 8 x i8> %1,
    <vscale x 8 x i8> %2,
    iXLen %3, iXLen 1)
  ret <vscale x 4 x i32> %a
}
